restaurants_db = [
    {"id": 1, "name": "Tartine Bakery", "city": "San Francisco"},
    {"id": 2, "name": "Zuni Cafe", "city": "San Francisco"},
    {"id": 3, "name": "House of Prime Rib", "city": "San Francisco"},
    {"id": 4, "name": "Swan Oyster Depot", "city": "San Francisco"},
    {"id": 5, "name": "Benu", "city": "San Francisco"},
    {"id": 6, "name": "Gary Danko", "city": "San Francisco"},
    {"id": 7, "name": "Tony's Pizza Napoletana", "city": "San Francisco"},
    {"id": 8, "name": "La Taqueria", "city": "San Francisco"},
    {"id": 9, "name": "State Bird Provisions", "city": "San Francisco"},
    {"id": 10, "name": "Slanted Door", "city": "San Francisco"},
    {"id": 11, "name": "Chez Panisse", "city": "Berkeley"},
    {"id": 12, "name": "La Mediterranee", "city": "Berkeley"},
    {"id": 13, "name": "Homeroom", "city": "Oakland"},
    {"id": 14, "name": "Commis", "city": "Oakland"},
    {"id": 15, "name": "Shakewell", "city": "Oakland"},
    {"id": 16, "name": "Burdell", "city": "Oakland"},
    {"id": 17, "name": "Soba Ichi", "city": "Oakland"},
    {"id": 18, "name": "Camino", "city": "Oakland"},
    {"id": 19, "name": "Brown Sugar Kitchen", "city": "Oakland"},
    {"id": 20, "name": "The Fat Lady", "city": "Oakland"},
    {"id": 21, "name": "n/naka", "city": "Los Angeles"},
    {"id": 22, "name": "Bestia", "city": "Los Angeles"},
    {"id": 23, "name": "Guelaguetza", "city": "Los Angeles"},
    {"id": 24, "name": "Spago Beverly Hills", "city": "Beverly Hills"},
    {"id": 25, "name": "République", "city": "Los Angeles"},
    {"id": 26, "name": "Roscoe's House of Chicken and Waffles", "city": "Los Angeles"},
    {"id": 27, "name": "Musso & Frank Grill", "city": "Los Angeles"},
    {"id": 28, "name": "Providence", "city": "Los Angeles"},
    {"id": 29, "name": "Din Tai Fung", "city": "Arcadia"},
    {"id": 30, "name": "In-N-Out Burger", "city": "Baldwin Park"},
    {"id": 31, "name": "Juniper & Ivy", "city": "San Diego"},
    {"id": 32, "name": "Phil's BBQ", "city": "San Diego"},
    {"id": 33, "name": "Hodad's", "city": "San Diego"},
    {"id": 34, "name": "Born & Raised", "city": "San Diego"},
    {"id": 35, "name": "The Crack Shack", "city": "San Diego"},
    {"id": 36, "name": "The French Laundry", "city": "Yountville"},
    {"id": 37, "name": "Bouchon Bistro", "city": "Yountville"},
    {"id": 38, "name": "Ad Hoc", "city": "Yountville"},
    {"id": 39, "name": "SingleThread", "city": "Healdsburg"},
    {"id": 40, "name": "Valette", "city": "Healdsburg"},
    {"id": 41, "name": "The Girl & The Fig", "city": "Sonoma"},
    {"id": 42, "name": "Tadich Grill", "city": "San Francisco"},
    {"id": 43, "name": "Foreign Cinema", "city": "San Francisco"},
    {"id": 44, "name": "House of Nanking", "city": "San Francisco"},
    {"id": 45, "name": "Cotogna", "city": "San Francisco"},
    {"id": 46, "name": "Quince", "city": "San Francisco"},
    {"id": 47, "name": "Rich Table", "city": "San Francisco"},
    {"id": 48, "name": "Liholiho Yacht Club", "city": "San Francisco"},
    {"id": 49, "name": "Rintaro", "city": "San Francisco"},
    {"id": 50, "name": "The Progress", "city": "San Francisco"}
]